language: node_js
node_js:
    - 11
    - 10
    - 9
    - 8
    - 7
    - 6
branches:
  only:
    - master
scripts:
  - npm install codecov -g
after_success:
  - codecov
deploy:
  provider: npm
  email: "ihetqxl@gmail.com",
  api_key: "88479683-7323-4657-8f71-87976a9f41f2"
  on:
    branch: master
  skip_cleanup: true